### ISSUE TITLE
US16 -  Eu como corpo docente/diretor desejo registrar notificações para informar o responsável e os próprios alunos.

### ISSUE THREAD

**Issue by LeonardoRk** [fga-gpp-mds/2017.1-Escola-X#17]
CRITÉRIOS DE ACEITAÇÃO

- [x] Somente o diretor e o corpo docente poderá registrar uma notificação.
- [x] Na parte superior de cada perfil, deverá existir o campo que permita registrar uma notificação.
- [x] Quando clicado neste campo de notificação, na próxima página deverá ser mostrado os campos que especifiquem o tipo da notificação (advertência,suspensão ou eventos escolares).
- [x] Toda notificação de advertência ou suspensão deve ser registrada com o nome do aluno, matrícula do mesmo e o motivo desta notificação.
- [x] Toda notificação realizada deve ser salva no perfil do aluno, para que o mesmo e seus responsáveis possam visualizar essas notificações.
- [x] Toda notificação quando realizada com sucesso, deverá mostrar uma mensagem alertando o responsável que realizou a ação de notificar sobre o sucesso desta notificação.
- [x] Toda notificação quando não realizada com sucesso, deverá ser mostrados os campos que impossibilitaram a realização da mesma.
- [x] Somente o diretor poderá registrar uma suspensão.
- [x] Nenhuma notificação poderá ser registrada com os campos de nome do aluno,matrícula e o responsável pela notificação em branco.
-  [x] O diretor poderá editar advertências e suspensões, além de poder excluí-las.
-  [x] O corpo docente poderá editar somente advertências, além de poder excluí-las.
-  [x] As alterações de edição e exclusão de advertências e suspensões devem ser atualizadas no perfil de cada estudante.
-  [x] Toda notificação do tipo de eventos escolares deve ser enviada para todos os alunos e seus responsáveis.
- [ ] Quando clicado para ver a notificação, deverá aparecer o nome do responsável pela notificação, a data e o motivo da notificação.

**Comment by andre-filho** [comment]
essa historia devia estar junto de advertencia porque muitos dos criterios sao de advertencia e a gente vai acabar tendo que implementar a historia deles no meio do caminho.
